charts/umbrella/charts/certs/values.yaml, charts/umbrella/values.yaml
Use the same secretnames as the [eclipse-tractusx/tractusx-edc chart](https://github.com/eclipse-tractusx/tractusx-edc/blob/95c9ee452b0892baec818fa71b4d0764b61bf08a/charts/tractusx-connector/values.yaml#L524-L529).
<hr />
=> chore(helm): use default daps secretsnames

charts/umbrella/values.yaml
=> fix: enable centralidp in values.yaml

charts/umbrella/Chart.yaml, charts/umbrella/values.yaml
feat: Add bpn-discovery helm chart
=> Add bpn-discovery helm

charts/umbrella/Chart.yaml, charts/umbrella/values.yaml
iam: change db subchart to standalone architecture to save runner resources
=> chore(iam): change db subchart to standalone architecture

.github/workflows/helm-checks.yaml, charts/umbrella/Chart.yaml, charts/umbrella/values.yaml
- add sd-factory 
for now with preliminary config
https://github.com/eclipse-tractusx/tractus-x-umbrella/issues/55
=> feat: add sd-factory

.github/workflows/helm-checks.yaml
chore(helm-checks): add simple-data-backend
=> chore(helm-checks): add simple-data-backend

.github/workflows/helm-checks.yaml
add tx-data-provider to helm checks
=> chore: add tx-data-provider to helm checks

charts/umbrella/Chart.yaml, charts/umbrella/values.yaml
- disable data consumer and provider until works and switch to released data provider chart: install issue will be solved by #67
- add config for managed-identity-wallet and update docs
=> chore: disable data consumer/provider and add config for miw

charts/umbrella/Chart.yaml, charts/umbrella/README.md, charts/umbrella/values-adopter-data-exchange.yaml, charts/umbrella/values-adopter-portal.yaml, charts/umbrella/values.yaml
- disable persistance for all components
- improve readme
- add some config to data consumer and provider
=> chore: disable persistance, add config and improve docs

charts/umbrella/Chart.yaml, charts/umbrella/values.yaml
=> chore: add edc ingress

charts/umbrella/Chart.yaml, charts/umbrella/templates/post-install-miw-setup.yaml, charts/umbrella/values-adopter-data-exchange.yaml, charts/umbrella/values.yaml
- add seeding job for MIW wallet creation. 
- Full EDC flow between dataconsumer and dataprovider was tested successfully (Catalog Request -> Contract Negotiation -> Transfer Process -> Dataplane Request)
=> chore: add MIW wallet creation

charts/tx-data-provider/Chart.yaml, charts/tx-data-provider/resources/Testdata_AsBuilt-combustion.json, charts/tx-data-provider/resources/transform-and-upload.py, charts/tx-data-provider/resources/upload-data.sh
- Update edc seedint to assets/v3 endpoint
- cleanup seeding script
=> chore: cleanup testdata seeding

charts/umbrella/Chart.yaml, charts/umbrella/values-adopter-data-exchange.yaml, charts/umbrella/values-adopter-portal.yaml, charts/umbrella/values.yaml
chore: add tx-data-provider v0.0.4 to don't seed testdata at upgrade #84
chore: disable persistentVolume for pgadmin4
=> chore: don't seed testdata at upgrade and improve pgadmin4

.gitignore, charts/umbrella/Chart.yaml, charts/umbrella/README.md, charts/umbrella/cluster-issuer.yaml
Update umbrella README.md for readability and structure. Add rudimentary differentiation between Linux, Windows and Mac section.
> As per discussion with @stephanbcbauer 
=> Update umbrella README, add rudimentary Windows section

simple-data-backend/src/main/java/org/eclipse/tractusx/simpledataservice/SimpleDataServiceController.java
- add "/{id}/$value" get mapping to simple data backend
=> chore: add "/{id}/$value" get mapping to simple data backend

CONTRIBUTING.md, LICENSE_non-code, NOTICE.md
=> docs: update legal docs according to the updated TRG7 guidelines

charts/values-test-iam-init-container.yaml
update of forgotten during https://github.com/eclipse-tractusx/tractus-x-umbrella/pull/94
=> chore: fix iam init container realm path

charts/tx-data-provider/Chart.yaml, charts/tx-data-provider/templates/_helpers.tpl, charts/umbrella/Chart.yaml, charts/umbrella/values.yaml
Upgrade helm version of DTR to 0.4.11 for Release 24.05
https://github.com/eclipse-tractusx/sig-release/issues/710
=> Upgrade dtr to 0.4.11 (Release 2024.05)

.github/workflows/trufflehog.yml
This PR contains the trufflehog workflow which was needs to be added as indicated in #120.
Closes #120
=> feat(workflow): created trufflehog workflow file

charts/umbrella/README.md
Merging fixes from closed PRs:
#124 and #123
=> chore: implemented open issues from closed PRs

charts/umbrella/Chart.yaml, charts/umbrella/README.md
Update the BDRS version to 0.5.2 #139
=> feat: Update BDRS version

docs/api/curl/UmbrellaConnectorDataExchange.md, docs/api/postman/UmbrellaConnectorData-Exchange.postman_collection.json
Update the postman collection and the curl commands to reflect the changes in policy creation payload.  
#158 
=> docs: Update postman and readme policy payload

charts/tx-data-provider/Chart.yaml, charts/umbrella/Chart.yaml
=> [DTR] Upgrade to R24.08

charts/umbrella/Chart.yaml, charts/umbrella/values.yaml
Fix typo bpndiscoveryEndpoint in umbrella values.yaml
=> Fix typo bpndiscoveryEndpoint in umbrella values.yaml

charts/tx-data-provider/Chart.yaml, charts/umbrella/Chart.yaml
Upgrade EDC to 0.8.0
Updates #193 
=> feat: upgrade EDC to 0.8.0

docs/concept/TAP7.1-solution-design.md
Update bundle structure documentation
=> Add Table to bundle structure

.github/workflows/chart-release.yaml
=> fix: add observability repositories into release pipeline

docs/concept/TAP7.1-solution-design.md
=> Update complexity reduction

docs/concept/TAP7.1-solution-design.md, docs/concept/solution-design-hausanschluss-bundle.md
=> docs: optimize chapters and improvements

README.md, docs/README.md, docs/user/guides/database-access.md, docs/user/guides/observability/observability.md, docs/user/guides/portal-usage.md, docs/user/installation/released-chart.md, docs/user/installation/uninstallation.md, docs/user/network/README.md, docs/user/network/tls.md, docs/user/note-r2405-onwards/README.md, docs/user/setup/README.md, docs/user/setup/semantic-hub.md
- update readme for ongoing upgrade to R25.03
- fix md format
https://github.com/eclipse-tractusx/tractus-x-umbrella/issues/226
=> docs: update readme for ongoing upgrade to R25.03 and fix md format

docs/concept/solution-design-hausanschluss-bundle.md
- Refine capability bundle structure in documentation
=> chore: Refine capability bundle structure in documentation

charts/tx-data-provider/Chart.yaml, charts/tx-data-provider/resources/Testdata_AsBuilt-combustion.json, charts/tx-data-provider/resources/transform-and-upload.py, charts/umbrella/Chart.yaml, docs/api/postman/UmbrellaConnectorData-Exchange.postman_collection.json, docs/user/guides/data-exchange/consume-data.md, docs/user/guides/data-exchange/provide-data.md
- update EDC to 0.9.0 https://github.com/eclipse-tractusx/tractus-x-umbrella/issues/236
- update BDRS to 0.5.4 https://github.com/eclipse-tractusx/tractus-x-umbrella/issues/233
The data exchange flow was tested (using "values-adopter-data-exchange.yaml") and verified to work with the updated test data.
=> feat: update EDC and BDRS to release 25.03

.github/workflows/helm-checks.yaml, charts/dataspace-connector-bundle/Chart.yaml, charts/dataspace-connector-bundle/values.yaml, charts/digital-twin-bundle/Chart.yaml, charts/digital-twin-bundle/values.yaml, charts/identity-and-trust-bundle/Chart.yaml, charts/identity-and-trust-bundle/values.yaml, charts/tx-data-provider/Chart.yaml, charts/tx-data-provider/values.yaml, charts/umbrella/Chart.yaml, charts/umbrella/templates/configmap-portal-testdata-seeding.yaml, charts/umbrella/values.yaml, charts/values-test-data-exchange.yaml, charts/values-test-shared-services-1.yaml, hack/helm-dependencies.bash
- downgrade EDC to 0.8.0 until https://github.com/eclipse-tractusx/tractus-x-umbrella/pull/260 is merged
- fix linting
- cleanup bundle values
=> chore: cleanup provider values, fix linting

README.md, charts/umbrella/Chart.yaml, docs/user/installation/README.md
Upgrade sd-factory to latest release compatible with R25.03.
Closes #232 
=> feat: update sd-factory

docs/user/guides/data-exchange/consume-data.md, docs/user/guides/data-exchange/provide-data.md
Add diagrams to e2e consumer and provider tests.
Fixing #180 issues.
=> docs: add diagrams to e2e consumer and provider tests

charts/umbrella/Chart.yaml, docs/user/installation/README.md
Upgrades BPDM to 6.0.0 as part of release/25.06. 
#290 
=> feat: upgrade bpdm to 6.0.0

docs/concept/adr-secret-management.md, docs/concept/solution-design-cloud-ready-infrastructure-automation.md
Adding a solution design concept for cloud ready infrastructure automation and an architecture decision record for the secret management with the goal to make the umbrella helm chart cloud ready.
=> docs: Added solution concept for cloud ready infrastructure automation
