eclipse-tractusx/tractus-x-umbrella

- .github/workflows/helm-test.yaml
This PR adds an initial workflow runs helm test with [chart-testing-action](https://github.com/helm/chart-testing-action) and `ct install`. To install the chart, a kind cluster using [kind-action](https://github.com/helm/kind-action).
The workflow itself is already prepared to run a matrix build to test the chart und multiple different kubernetes  versions.
The strategy is configured to only allow 1 parallel build to avoid race conditions of parallel `kubectl` commands (potential context issues).
fixes #3
> feat(build): add initial workflow for helm testing

- .github/workflows/chart-release.yaml
This PR adds an initial workflow to release the Helm Charts contained in this repositories. 
It uses [chart-releaser-action](https://github.com/helm/chart-releaser-action) to package the chart and create a GitHub release.
The necessary branch `gh-pages` is already available.
fixes #4
> feat(build): add initial chart release workflow

- charts/umbrella/README.md
- hack/helm-dependencies.bash
Currently the charts/umbrella Helm chart requires download not only from its dependencies but also their dependency (recursive).
This PR adds a hack-script for a simpler download of these recursive dependencies.
closes #7
> feat: add hack script for charts/umbrella recursive dependencies

- charts/umbrella/charts/certs/templates/job-daps.yaml
- charts/umbrella/charts/certs/templates/job-vault.yaml
- charts/umbrella/charts/certs/values.yaml
- charts/umbrella/values.yaml
In other tx [charts](https://github.com/eclipse-tractusx/tractusx-edc/blob/c5b61db65413d130b6f521b76cf32285e65a6aad/charts/tractusx-connector/values.yaml#L530-L532) the name of the daps and vault is url not address.
This change will change the certs dependency chart to have the same structure.
Also the `.Release.Name` will be included in the url in the default values.
This will currently automatically be overwritten by the umbrella chart in the same way:
https://github.com/eclipse-tractusx/e2e-testing/blob/fcabc2a2e938951c0a9e2de81833c5401d4c23bf/charts/umbrella/values.yaml#L65-L66
https://github.com/eclipse-tractusx/e2e-testing/blob/fcabc2a2e938951c0a9e2de81833c5401d4c23bf/charts/umbrella/values.yaml#L78-L79
This change will affect both daps and vault.
<hr />
Marco Lecheler …
> chore(helm): use url instead of address value key for certs chart

- charts/umbrella/charts/certs/templates/job-daps.yaml
Some fields of the `certs` dependency chart are mandatory.
This PR will add the required check for those:
- `.Values.daps.auth.clientId`
- `.Values.daps.auth.clientSecret`
- `.Values.daps.edc.clientId`
<hr />
> chore(helm): set certs dep-chart required values

- .github/kyverno-policies/require-run-as-nonroot.yaml
- .github/workflows/kyverno.yaml
Add Kyverno validation workflow
A GitHub workflow to run on pull requests when a chart is changed in the repository. Kyverno will validate different aspects of the chart. Currently the single validation enabled is that pods (and other resources managing pods) have the `runAsNonRoot` security context enabled. Chart testing is running first to detect if any of the charts are changed. Then it dispatches as many Kyverno validation jobs in a matrix as needed for every changed chart.
Fixes #12 
- To request a review, check out [who's involved](https://projects.eclipse.org/projects/automotive.tractusx/who) to see a list of contributors and committers
- Use the [mailing …
> chore: add kyverno validation workflow

- charts/umbrella/charts/certs/templates/job-daps.yaml
The job for registering the certificates on the daps should run as nonRoot job.
- related with policy enforcement for nonRoot in #28
<hr />
> chore: enforce nonRoot for daps certs

- charts/umbrella/charts/certs/templates/configmap-daps.yaml
- charts/umbrella/charts/certs/templates/configmap-vaultscript.yaml
Currently there is no information in the job log of the `certs` dependency chart to which daps / vault the connection is established.
This PR will add the address to the configmap thus the address will added in the pod log.
<hr />
> chore(helm): add url to connecting instance for certs chart

- charts/umbrella/values.yaml
Enable networkPolicy for vault dependency for the umbrella chart.
<hr />
> chore: add networkPolicy enabled for vault dependency

- charts/umbrella/Chart.yaml
- charts/umbrella/templates/_helpers.tpl
- charts/umbrella/values.yaml
This PR adds the helm charts from portal and cx-iam (versions from 3.2/23.09 release) to the umbrella chart.
It doesn't contain tests in [this sense](https://helm.sh/docs/helm/helm_test/#helm) and for a proper proper e2e testing functional tests as wells as more config would need to get added, still, for an initial integration in the umbrella helm chart this PR should be sufficient.
> feat: add initial setup for portal and cx-iam

- .github/workflows/helm-checks.yaml
It states that helm and python must be installed for the [chart-testing-action](https://github.com/helm/chart-testing-action?tab=readme-ov-file#example-workflow).
> fix: add setup-helm step as required by chart-testing-action

- .github/workflows/helm-checks.yaml
- charts/umbrella/Chart.yaml
feat: upgrade portal and iam subcharts to 23.12 release
chore(helm checks): run on every pr and rename workflow
> feat: upgrade portal and iam subcharts to 23.12 release

- charts/umbrella/Chart.yaml
- charts/umbrella/values.yaml
- upgrade portal and iam to 24.03 release
- also: move to standalone db setup for portal to save resources
> chore: upgrade portal and iam to 24.03 release

- .github/workflows/helm-checks.yaml
- charts/umbrella/values.yaml
`ct install` step in the helm checks workflow for the umbrella chart kept running into the following error:
```
Error: INSTALLATION FAILED: client rate limiter Wait returned an error: rate: Wait(n=1) would exceed context deadline
```
Presumably due to some cpu throttling in combination with [chart-testing](https://github.com/helm/chart-testing)
change to `helm install` instead of `ct install` to don't run into that error anymore because when using helm install (also on local Minikube) the chart (for instance for this PR https://github.com/eclipse-tractusx/tractus-x-umbrella/pull/53) installs without error.
also: add an informational step to describe the node for more awareness about available resources in the future and upgrade some actions
I attempted different measure until coming …
> chore: fix helm checks workflow for client rate limiter error

- charts/umbrella/Chart.yaml
- charts/umbrella/README.md
- charts/umbrella/templates/centralidp-spi.yaml
- charts/umbrella/templates/sharedidp-spi.yaml
- charts/umbrella/values.yaml
Fixes #58 
add configuration:
update docs (chart readme and description)
> feat: add config to portal, iam and discoveryfinder and update docs

- .github/workflows/chart-release.yaml
Chart release workflow now fails when PR is merged and the tag/release already exists. We want to skip the release action instead.
> fix: skip chart release on existing tag or release

- charts/umbrella/Chart.yaml
- charts/umbrella/values.yaml
By default the bpn discovery and discovery finder charts use 50Gi PVCs. It might be reasonable in a production environment but we want to decrease the footprint of the umbrella chart when deploying on a local machine or running tests. Therefore I reduced the PVC sizes to 8Gi.
> chore: lower the pvc size for bpndiscovery and discoveryfinder

- .github/workflows/helm-checks.yaml
- charts/umbrella/Chart.yaml
- charts/umbrella/README.md
- charts/umbrella/values-adopter-data-exchange.yaml
- charts/umbrella/values-adopter-portal.yaml
- charts/umbrella/values.yaml
- charts/values-test-data-exchange.yaml
- charts/values-test-iam-init-container.yaml
- charts/values-test-shared-services.yaml
fix tx-data-provider: 
- allow provider and consumer being enabled at the same time (relates to https://github.com/eclipse-tractusx/tractus-x-umbrella/pull/67)
- adjust adopter values files and docs
chart testing: 
- split install into shared-services and data-exchange
- disable all components in default values file
chore(iam): change to imagePullPolicy IfNotPresent
> chore: rework chart testing and tx-data-provider

- charts/umbrella/Chart.yaml
- charts/umbrella/values.yaml
add tls.crt to truststore from miw to enable https connection with centralidp Keycloak instance
to not run into the following exception at managed-identity-wallet:
"status": 500,
"error": "Internal Server Error"
`PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`
https://github.com/eclipse-tractusx/sig-release/issues/418
> chore(miw): enable https connection with centralidp

- charts/umbrella/Chart.yaml
- charts/umbrella/README.md
- charts/umbrella/values.yaml
- concept/seeds-overall-data.md
- init-container/iam/centralidp/CX-Central-realm.json
- init-container/iam/sharedidp/CX-Operator-realm.json
- init-container/iam/sharedidp/CX-Operator-users-0.json
- change from `example.org` to `tx.test` as test domain
`example.org` is a reserved (2nd level) domain (for documentation purposes) and therefore it's not optimal for dns resolution.
This change may make the editing of the etc/hosts file less necessary: https://github.com/eclipse-tractusx/tractus-x-umbrella/blob/main/charts/umbrella/README.md#network-setup
https://github.com/eclipse-tractusx/sig-release/issues/418
> chore: change from example.org to tx.test

- charts/umbrella/Chart.yaml
- charts/umbrella/values-adopter-data-exchange.yaml
- charts/umbrella/values.yaml
- add config in adopter values file to make override of relevant values clearer
- remove disabled components from adopter values file as they defaulting to disabled by now 
- why no tls connection?:
-  tls.crt from root-secret can't get imported into truststore of the tractusx-connector, at least not automatically: the customCaCerts option exists but that would require to copy the autogenerated tls.crt into the values file
- when attempting the option with customCaCerts, the flow doesn't e2e due to the miw being unable to verify the jwt signature of the centralidp, even if the tls.crt from the root-secret is imported into the truststore of the miw
> fix(dataexchange): change to http connection and add config

- charts/tx-data-provider/Chart.yaml
- charts/tx-data-provider/templates/post-install-job-upload-testdata.yaml
- charts/tx-data-provider/templates/post-install-vault-setup.yaml
enable post-upgrade hook and add imagePullPolicy for postinstall jobs of tx-data-provider
post-upgrade hook is needed for dataconsumerTwo
https://github.com/eclipse-tractusx/sig-release/issues/418
> chore: enable post-upgrade hook and add imagePullPolicy

- charts/umbrella/Chart.yaml
- charts/umbrella/README.md
- charts/umbrella/values-adopter-data-exchange.yaml
- charts/umbrella/values-adopter-portal.yaml
- charts/umbrella/values.yaml
- add dataconsumerTwo: disabled by default, to be installed at upgrade of data exchange subset
required https://github.com/eclipse-tractusx/tractus-x-umbrella/pull/81
- add pgadmin4 instance for database access
- change to portal 1.8.1 and complete config
https://github.com/eclipse-tractusx/sig-release/issues/418
> chore: add dataconsumerTwo, pgadmin4 and improve portal

- charts/umbrella/Chart.yaml
- hack/helm-dependencies.bash
Trying to fix the helm dependency hack script that is currently failing [here](https://github.com/eclipse-tractusx/tractus-x-umbrella/actions/runs/9059263005/job/24889079879?pr=84#step:11:19).
> fix: add runix helm repo to the dependency hack script

- charts/tx-data-provider/Chart.yaml
- charts/tx-data-provider/templates/post-install-job-upload-testdata.yaml
- charts/umbrella/Chart.yaml
- hack/helm-dependencies.bash
fix: do not seed testdata again on upgrade
introduced with https://github.com/eclipse-tractusx/tractus-x-umbrella/pull/81
> fix(tx-data-provider): do not seed testdata again on upgrade

- charts/umbrella/Chart.yaml
- charts/umbrella/README.md
- charts/umbrella/values.yaml
We are hardcoding the postgresql database passwords for the postgres and custom users as well wherever possible to help users with authentication and pgadmin4 usage. The password pattern will be `dbpassword<productname>`.
I'll update the description with every modified component.
> feat: hardcode postgres passwords

- .github/workflows/helm-checks.yaml
- charts/umbrella/Chart.yaml
- enable chart testing workflow to determine target branch based on pull request base
necessary because we're enabling the upgrade to R24.05 in another branch than main and the missing enabling blocks the review of https://github.com/eclipse-tractusx/tractus-x-umbrella/pull/106
> chore(helm-test): determine target branch based on pr base

- charts/umbrella/Chart.yaml
- charts/umbrella/README.md
- charts/umbrella/values.yaml
Upgrade Portal to v2.0.0 and, Centralidp to Sharedidp to v3.0.0
In this comment it is requested to do the upgrade in one pull request https://github.com/eclipse-tractusx/tractus-x-umbrella/pull/106#discussion_r1670723925
It will allow compatibility with the BPDM component https://github.com/eclipse-tractusx/tractus-x-umbrella/pull/106#issuecomment-2237960243 
- [ x ] Tested Login, forgot password and company invitation
- [ x ] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [ x ] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all …
> Chore: upgrade portal and iam

- .github/workflows/helm-checks.yaml
- charts/values-test-shared-services-1.yaml
- charts/values-test-shared-services-2.yaml
- split shared services
- remove components which are anyway disabled by default
reached resource limits with adding BPDM 
https://github.com/eclipse-tractusx/tractus-x-umbrella/pull/106
> chore: rework chart testing

- charts/umbrella/README.md
* enhance portal description to provide a script to skip the clearinghouse step for a successful onboarding
Without the script the clearinghouse step will fail, since there isn't a clearinghouse FOSS application
Refs: #115
> docs(portal): enhance documentation for onboarding process

- charts/umbrella/Chart.yaml
- charts/umbrella/values.yaml
Update the SSI-Credential-Issuer version to 1.1.0 [#135](https://github.com/eclipse-tractusx/tractus-x-umbrella/issues/135)
> feat: Update SSI-Credential-Issuer version

- charts/tx-data-provider/Chart.yaml
- charts/tx-data-provider/resources/Testdata_AsBuilt-combustion.json
- charts/umbrella/Chart.yaml
> feat: upgrade EDC to 0.7.7

- charts/umbrella/Chart.yaml
- charts/umbrella/values.yaml
The urls are belonging to the control plane. So we should state "controlplane" in the seeding urls.
> chore: updated edc urls

- docs/user/guides/data-exchange/consume-data.md
- docs/user/guides/data-exchange/provide-data.md
- docs/user/setup/README.md
This PR adds some improvements, restructuring within the data exchange documentation. It also adds requests and expected responses to get a more in-depth understanding of the flow. The currently documented flow was tested multiple times.
@dvg36 would be cool to test it again, just to be sure!!! I think after this, we are well-prepared for the Tractus-X Community Days. ;)
> docs(data exchange): adapt and restructure the data exchange

- docs/README.md
- docs/user/network/README.md
- docs/user/setup/README.md
This PR extends the setup and network documentation with a way to go for people who have no access to docker desktop because of license issues in their companies (or whatever reason) on macOS. It also supports more complicated company setups with proxys and custom certificate chains.  The currently documented flow was tested multiple times.
> docs(kubernetes setup): add support for people without docker desktop on macOS

- docs/user/setup/iatp-mock.md
#184 
Fix incorrect iatp-mock directory in [doc](https://github.com/eclipse-tractusx/tractus-x-umbrella/blob/main/docs/user/setup/iatp-mock.md#precondition-build-the-iatp-mock-docker-image)
> docs: fix incorrect iatp-mock directory

- .github/workflows/helm-checks.yaml
- README.md
- charts/umbrella/Chart.yaml
- charts/umbrella/templates/configmap-portal-testdata-seeding.yaml
- charts/umbrella/values.yaml
- charts/values-test-data-exchange-iatp-mock.yaml
- charts/values-test-data-exchange.yaml
- charts/values-test-iam-init-container.yaml
- charts/values-test-shared-services-1.yaml
- charts/values-test-shared-services-2.yaml
- docs/user/installation/README.md
- docs/user/network/README.md
- init-container/iam/centralidp/CX-Central-realm.json
upgrade keycloak instances, portal and issuer to R24.12
as well as update and fix documentation
and refactor helm chart testing to first install centralidp (keycloak) and to wait for seeding job to finish
- https://github.com/eclipse-tractusx/tractus-x-umbrella/issues/186
- https://github.com/eclipse-tractusx/tractus-x-umbrella/issues/185
- https://github.com/eclipse-tractusx/tractus-x-umbrella/issues/187
> feat: upgrade keycloak instances, portal and issuer to R24.12

- charts/umbrella/Chart.yaml
- charts/umbrella/values.yaml
This PR resolves the issue where the participant onboarding process in the Portal gets stuck at the BPN creation step, preventing the Wallet creation step from proceeding.
Fixes #209 
> fix: BPN Creation Gets Stuck During Portal Onboarding

- docs/user/guides/portal-usage.md
**The PR #208 was no more valid due to the declining of an ECA agreement**
The wallet creation step was getting failed during the participant onboarding [here](https://github.com/eclipse-tractusx/tractus-x-umbrella/blob/main/docs/user/guides/portal-usage.md#performing-participant-onboarding), .
In the original portal values, the `didDocumentPath` is set to `/api/administration/staticdata/did`.
Documented the step to set the endpoint to an empty string in the ssi-dim-wallet-stub values file.
https://github.com/eclipse-tractusx/tractus-x-umbrella/issues/197#issuecomment-2615382083
> docs: add Identity wallet creation step to the participant onboarding

- .github/workflows/helm-checks.yaml
Replaced the semanticHub version in the Helm-Check workflow.
Closes #221 
> fix: Replace semanticHub version in Helm-Check workflow

- charts/umbrella/Chart.yaml
- charts/umbrella/values-adopter-data-exchange-observability.yaml
Fixes scraping of prometheus JVM metrics due to pointing to default 9464 port, instead of tractusx-edc's 9090.
Outcome of [following discussion](https://github.com/eclipse-tractusx/tractusx-edc/issues/1905#issuecomment-2829829970)
> fix(Observability): fixed alignment of prometheus port for JVM metrics

- charts/umbrella/Chart.yaml
- docs/user/installation/README.md
Upgrade ssi-credential-issuer to latest release compatible with R25.03
Closes #231 
Onboarding completed without a problem with the new version:
> feat: Upgrade ssi-credential-issuer to R25.03

- charts/umbrella/Chart.yaml
- charts/umbrella/values.yaml
- docs/user/guides/database-access.md
with other integrated configuration:
-  replica count to 1 to not waste resources
- processIdentity can fall back to values file from issuer chart
- password pattern of other postgres dependencies
- add nameOverride for issuer postgres dependency
- update db access docs
noticed in the course of checking #273
> fix: align issuer configuration

- charts/umbrella/Chart.yaml
- charts/umbrella/values.yaml
The  setting under  is never used in this chart and only confuses new adopters who see Keycloak creds configured elsewhere. Drop the two lines to clean up defaults.
This PR removes the two lines:
```yaml
keycloak:
enabled: false
```
from the `ssi-dim-wallet-stub` section of the umbrella chart’s `values.yaml`. These fields aren't needed for this chart (we never spin up a testing Keycloak instance for that stub).  It rather confuses new users who see Keycloak credentials configured under `ssi-dim-wallet-stub.keycloak` but assume they must also toggle `enabled: true` here. See:
```yaml
ssi-dim-wallet-stub:
wallet:
replicaCount: 1
[...]
keycloak:
realm: "CX-Central"
authServerUrl: "http://centralidp.tx.test/auth"
service:
type: ClusterIP
port: 8080
keycloak:
enabled: false
```
More clarity …
> chore(umbrella): Remove unused keycloak.enabled flag from ssi-dim-wallet-stub

- docs/user/network/README.md
This PR adds a Troubleshooting section to the Tractus-X Umbrella Configuration and Networking documentation. It includes a description of and a solution to an issue related to domain name resolution. The problem may occur even when all existing instructions in the documentation are followed correctly.
The issue may arise due to specific DNS settings in the company's environment. Including the solution in the documentation could help save time for other users facing a similar problem.
Closes #300
> docs: troubleshooting section for dns related issues

- charts/tx-data-provider/Chart.yaml
- charts/tx-data-provider/templates/post-install-job-upload-testdata.yaml
- charts/tx-data-provider/templates/post-install-vault-setup.yaml
- charts/tx-data-provider/values.yaml
- charts/umbrella/Chart.yaml
This PR allows for overriding the image tag in the testdata and vault setup hooks.
We had some issues with image fetching directly from Docker Hub being blocked, possibly due to request limiting. With this change, we will be able to fetch the image through ACR which acts as a proxy, with caching rules to prevent too many requests to Docker Hub.
> feat: Add possibility of overriding image in testdata and vault setup
